name: Running Action- log
on:
  workflow_dispatch:
    inputs:
      PAYLOAD:
        description: 'Payload'
        required: false

jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    container: ghcr.io/nolcut/github-actions-python:v0.1.1
    env:
      SECRET_PAYLOAD: ${{ secrets.SECRET_PAYLOAD }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PAYLOAD_REPO: ${{ vars.PAYLOAD_REPO }}
      PAYLOAD: ${{ github.event.inputs.PAYLOAD }}
    steps:
    - name: run python
      run: |
        cd /action
        python3 faasr_start_invoke_github_actions.py
